# Логи генератора в формате JSON (см. JsonFormatter в traffic_gen.py)

input {
  beats {
    port => 5044
  }
}

filter {
  json {
    source => "message"
  }
  date {
    match => ["timestamp", "ISO8601"]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["http://10.10.10.13:9200"]
    index => "appserver-transactions-%{+YYYY.MM.dd}"
  }
}
